version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    hostname: backend
    depends_on:
      - mongodb
    networks:
      app-network:
        ipv4_address: 173.23.0.3

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./backend/.env
    command: mongod --auth
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.23.0.0/16
          gateway: 173.23.0.1
